import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { CiTwitter } from "react-icons/ci";
import { FaInstagram } from "react-icons/fa";
import { CiLinkedin } from "react-icons/ci";

export default function Home() {
  return (
    <div className="container mx-auto px-4 py-8">
      {/* Head Section */}
      <Head>
        <title>Our Story</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Content */}
      <main className="flex flex-col gap-8">
        {/* Our Story Section */}
        <h1 className="text-4xl font-bold text-left">Our Story</h1>
        <div className="flex gap-8 items-center">
          <div className="w-1/2">
            <p className="text-lg text-gray-700">
              Launched in 2015, Exclusive is South Asia's premier online shopping marketplace with an active presence in Bangladesh. Supported by a wide range of tailored marketing, data, and service solutions, Exclusive has 10,500 sellers and 300 brands and serves 3 million customers across the region.
            </p>
            <p className="text-lg text-gray-700 mt-4">
              Exclusive has more than 1 million products to offer, growing at a very fast rate. Exclusive offers a diverse assortment in categories ranging from consumer products.
            </p>
          </div>
          <div className="w-1/2">
            <Image
              src="/girls.jpeg"
              alt="Our Story"
              width={600}
              height={400}
              className="rounded-md shadow-md"
            />
          </div>
        </div>
      </main>

      {/* Four Boxes Section */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 py-12">
        <div className="bg-white rounded-lg shadow-md p-6 text-center">
          <Image
            src="/icon1.png"
            alt="Icon 1"
            width={50}
            height={50}
            className="mx-auto"
          />
          <h3 className="text-xl font-bold text-gray-800 mt-4">Fast Delivery</h3>
          <p className="text-gray-600 mt-2">Get your products quickly and efficiently.</p>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6 text-center">
          <Image
            src="/icon2.png"
            alt="Icon 2"
            width={50}
            height={50}
            className="mx-auto"
          />
          <h3 className="text-xl font-bold text-gray-800 mt-4">Secure Payment</h3>
          <p className="text-gray-600 mt-2">Enjoy safe and reliable payment options.</p>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6 text-center">
          <Image
            src="/icon3.png"
            alt="Icon 3"
            width={50}
            height={50}
            className="mx-auto"
          />
          <h3 className="text-xl font-bold text-gray-800 mt-4">24/7 Support</h3>
          <p className="text-gray-600 mt-2">We are here to help anytime, anywhere.</p>
        </div>
        <div className="bg-white rounded-lg shadow-md p-6 text-center">
          <Image
            src="/icon4.png"
            alt="Icon 4"
            width={50}
            height={50}
            className="mx-auto"
          />
          <h3 className="text-xl font-bold text-gray-800 mt-4">Diverse Products</h3>
          <p className="text-gray-600 mt-2">Choose from a wide range of categories.</p>
        </div>
      </div>

      {/* Meet Our Team Section */}
      <div className="py-12">
        <h2 className="text-4xl font-bold text-left mb-8">Meet Our Team</h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {[
            {
              name: 'Tom Cruise',
              role: 'Founder & Chairman',
              img: 'https://s3-alpha-sig.figma.com/img/0881/49fd/5afc043392ee3cbb529f429b3e2098d3?Expires=1734307200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=D1dLk2K~Gk5MKs~1B6CH~xHrU5MnkxLaMGTT2x1ED6O9jl89dUwdzY29qipifa06cTwZ01weZQxszfTsoLPT7LEStGI-U6gsF3ksy6LH0CFMiX3yg10NeimY8ad~DhL6kNRKuJktH4voTofLjWvsfG82JZVH3nA1tiMscnYKvsTNpsvpdNmJqsMiuZzBj1qPoOj-of-NvjWwJrcZ3UaWb8qJ6PEIL8d49lAvP1poKM3v3cSXiw6V~7YhZJQm6gWFXB78iCkbYPYEYW0WXqBD8Y8CYDB9qtS7V8cnU~d5t6ZiXMK6iu3yQzt3bMifuzxZYffJpoSIoI87broNQ8nN9w__',
            },
            {
              name: 'Emma Watson',
              role: 'Managing Director',
              img: 'https://s3-alpha-sig.figma.com/img/8438/eab9/a2fe88af0272adecd83422d0cb7e20d7?Expires=1734307200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=EgRepsaB1MI1UPw33R~uXfLZUG2vLJDlLY2V7XVT53HSiATlQvbYh6iWhXfB-m2spQGWmga-AANuYZzzZmz6UX9mEF1~KK95j1kmCi~PPWOH59Nk0o6VQm5iORGvq8BK9SvQo1QTnFy1fDVVRmmrHgnqtv3uujmoVYXGCF7fBSsKqA6PiW-5uD~oFJkFnrUcvd0l2r7QYHVtLG0HcX9V2FNrtVwDaP8aIqSEdkmJhqwa5ePrFA2IGrH48ZTFjNmFyDcRi7QCGUEqw3CQx-KKYi1ugd9PQjbAktID0fRnUETpz5~7fYagCincdjwC0YBTzq5JjnfBauZoZONz5rhDEA__',
            },
            {
              name: 'Will Smith',
              role: 'Product Designer',
              img: 'https://s3-alpha-sig.figma.com/img/ede4/8f2b/5df8103b281240ce5bafe5dd7d215ab8?Expires=1734307200&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=TnmOrS4kuuUVejl3FM1OYEQZe1YCUDr2lgzUJiq2upj6RjxvRwM9pA2zIt23QYtviQ2GhI9~eaCIoWZPBlZDP9Bt-qJJX7WJnsintHB4z3Brwv4YzozmmmlnUoUr04BLny9S-c~egZaHHkv-GrMJoAvmr9NHLKGrgyMlDaTblM3r32rjQAqf79~qe0pdsqlHqp7jiHus1tc4J5gVaDm8JwCFpGZPLaKnnqyLY8APIbPbXT2xqe85vgie-k~HR7i4yhyJzkEYbY-UPDdo1ewPgEkaNNjM3tKe0wL8nPZHZTmWzMdcD-xwSfAajokkuDyR8NE28nlSWUSVvomDWSALzA__',
            },
          ].map((member, index) => (
            <div
              key={index}
              className="bg-white shadow-lg rounded-lg overflow-hidden"
              style={{ width: "150px", height: "350px", margin: "auto" }}
            >
              <div
                className="relative"
                style={{ height: "300px", overflow: "hidden" }}
              >
                <img
                  src={member.img}
                  alt={member.name}
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="p-4 text-center">
                <h3 className="text-2xl font-bold text-gray-800">{member.name}</h3>
                <p className="text-gray-600">{member.role}</p>
                <div className="mt-4 flex justify-center gap-4">
                  <a href="#" className="text-blue-500 hover:text-blue-700">
                    <i className="<CiTwitter />"></i>
                  </a>
                  <a href="#" className="text-blue-500 hover:text-blue-700">
                    <i className="<FaInstagram />"></i>
                  </a>
                  <a href="#" className="text-blue-500 hover:text-blue-700">
                    <i className="<CiLinkedin />"></i>
                  </a>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
